### ISSUE TITLE
Couldn't parse plan

### ISSUE THREAD

**Issue by mrechte** [dalibo/pev2#119]
Hello,
On https://explain.dalibo.com/, I tried the following plan / SQL:
```
Bitmap Heap Scan on a
   Recheck Cond: ((id = 42) OR (id = 4711))
   ->  BitmapOr
         ->  Bitmap Index Scan on a_pkey
               Index Cond: (id = 42)
         ->  Bitmap Index Scan on a_pkey
               Index Cond: (id = 4711)

SELECT id FROM a
WHERE id = 42
   OR id = 4711
```

I got the error "Couldn't parse plan"

**Comment by pgiraud** [comment]
Thanks for the report.
It looks like depesz also struggles when trying to parse this plan.
Can you please either export the plan in JSON format or provide some SQL to build the a relation with data so that I can run the explain on my machine?

**Comment by pgiraud** [comment]
Nevermind, I was able to rebuild the data myself.

**Comment by pgiraud** [comment]
@mrechte for your information, the plan is correctly parsed when using COSTS ON mode.
```
 Bitmap Heap Scan on a  (cost=8.60..16.01 rows=2 width=4)
   Recheck Cond: ((id = 42) OR (id = 4711))
   ->  BitmapOr  (cost=8.60..8.60 rows=2 width=0)
         ->  Bitmap Index Scan on a_id_key  (cost=0.00..4.30 rows=1 width=0)
               Index Cond: (id = 42)
         ->  Bitmap Index Scan on a_id_key  (cost=0.00..4.30 rows=1 width=0)
               Index Cond: (id = 4711)
```

**Comment by pgiraud** [comment]
Do you confirm that you used "EXPLAIN (COSTS OFF) SELECT …".
I'm afraid it's very complicated to parse such a plan though it looks very simple.

**Comment by mrechte** [comment]
Yes, it was run with COSTS OFF option.
