### ISSUE TITLE
EXPLAIN SETTINGS

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#126]
New in PG12:

```
explain (analyze, settings) select * from pg_class ;

 Seq Scan on pg_class  (cost=0.00..17.99 rows=499 width=267) (actual time=0.039..0.494 rows=494 loops=1)
 Settings: effective_io_concurrency = '100', enable_partitionwise_aggregate = 'on', enable_partitionwise_join = 'on', from_collapse_limit = '10', join_collapse_limit = '10', max_parallel_workers = '4', random_page_cost = '1', temp_buffers = '32MB', work_mem = '30MB'
 Planning Time: 6.615 ms
 Execution Time: 1.190 ms
```

 - It should appear somewhere
 - in the future : these settings (here or their default value) may be interesting:  enable_*  to show that some nodes were deactivate ;  a comparison between work_mem and a temporary files ; join_collapse_limit against the number of joins...

**Comment by AbelVM** [comment]
I just came here to request this very feature!! :stuck_out_tongue_closed_eyes: 

Some more info about `SETTINGS`

https://fluca1978.github.io/2019/12/05/Explain_settings.html

It looks quite interesting!
