### ISSUE TITLE
Tables & indexes list

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#149]
While looking at a plan, I just had this question "how does PG access this table?". Currently I must search which node has the table as target. This takes time.

Suggestion: 
- list the tables somewhere (left pane, below?) 
- when I click on a table name, the focus goes to the first node using this table
- when there are more than one use of a table, just cycle between the nodes.
- show tables and their aliases ; a table with 2 different aliases should be listed twice (as 2 different tables).

Suggestion 2 : same thing for indexes (another tab of the same pane ?)
This could be useful, as some nodes list the table, and others the index.

**Comment by Krysztophe** [comment]
As just discussed:
  - items 2 and 3 are resolved by using Ctrl-F

So a list of tables/indexes/aliases would suffice, perhaps with links to the nodes.

**Comment by pgiraud** [comment]
It can still be improved but this has been taken into account with the addition of the stats tab.
