### ISSUE TITLE
Use dots instead of background color for highlights

### ISSUE THREAD

**Issue by pgiraud** [dalibo/pev2#179]
To make sure that the length of the text doesn't make the alert bigger.

**Comment by pgiraud** [comment]
It could look like this.
![Capture du 2020-04-16 10-56-26](https://user-images.githubusercontent.com/319774/79436533-4b832600-7fd1-11ea-8eb6-710e282b875d.png)

Second option with triangles.
![Capture du 2020-04-16 10-50-53](https://user-images.githubusercontent.com/319774/79436545-4f16ad00-7fd1-11ea-9ecb-d958c1ee2b16.png)

Current option.
![Capture du 2020-04-16 10-54-35](https://user-images.githubusercontent.com/319774/79436569-563dbb00-7fd1-11ea-8c96-82ff2a2e5793.png)

Opinions?

**Comment by jankatins** [comment]
I have usually very big graphs and the background stands out nicely, the smaller dots and triangles, as far as it can be judged by the examples above, not so much.
