### ISSUE TITLE
Parallelism not obvious enough

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#203]
The numbers in the following plans may be misleading: https://explain.dalibo.com/plan/DxW 

This is a simple filter on a 100k lines table with 5 workers+main process. Each one reads 1/6 of the table (16'667), keeps 8381 lines (as shown in the Parallel Scan node) ; total 50'287 lines in the uppermost node. There is a "Workers : 5". So all data is there ...

... but a miscount is easy if you miss that there is some parallelism (this is not so common). So you read "~16 667 scanned → ~8 381 returned"  (but this is in fact 100k / 50k) and wonder how to can have 50k lines on upper nodes..
Same for the Sort node: it sorts individually 8381 lines, but there are 50k to be sorted.

**Suggestion** : add a bold '' x 6 loops'' just after the show numbers. 
(''x 6 workers'' would be incorrect ; the main process may or may not be part of the parallelization).

This is worse in the "Compact" mode, where the only visual clue for parallelism is the stack (easy to miss, difficult to count).

This is more dangerous in the left diagram, where there is no indication that a node is parallelized, and others not. 
**Suggestion** : add " x 6 loops" in the tooltip
**Suggestion 2** (probably overkill) :  Repeat each node for each worker, to SEE the different workers. They do run in parallel after all. Could become difficult to read with the biggest queries...

**Comment by pgiraud** [comment]
The latest version of PEV2 including a new way to count rows (and related values) have been deployed on explain.dalibo.com.
The example plan you have provided now shows more consistent row numbers. Can you please give it a look? And close the current issue if it is fixed in your opinion?

**Comment by Krysztophe** [comment]
That's much better now, I close the issue.

Merci!
