### ISSUE TITLE
Store deletion link in local storage

### ISSUE THREAD

**Issue by KangOl** [dalibo/pev2#219]
This will allow users to not have to bookmark it or losing it by an unfortunate refresh.

A list of the user's plans can also be shown.

**Comment by pgiraud** [comment]
@KangOI this is not part of PEV2 itself. This is more about explain.dalibo.com which is a different project (relying on PEV2).
I fully understant this feature request and will try to address it as soon as possible.
Leaving the current issue open for future reference.

**Comment by pgiraud** [comment]
This is now available in explain.dalibo.com.
