### ISSUE TITLE
Impossible to view details for node with "Rows Removed by Join Filter" property

### ISSUE THREAD

**Issue by pestaa** [dalibo/pev2#224]
Hi!

Great project, I'm having a blast with it.

Unfortunately, some of my nested loops are crazy slow.

However, the node wouldn't open like the others do. Here's the console output:

![image](https://user-images.githubusercontent.com/187342/84500741-6b735500-acb5-11ea-9375-d9936aa3196f.png)

If you happen to have a look into it... thank you very much.

Have a nice day!

**Comment by pgiraud** [comment]
Thanks a lot!

This looks like a bug. Could you please share the corresponding plan?

**Comment by pestaa** [comment]
Thanks for the quick response!

I spent a little time on this and found that the node tries to display `Rows Removed by Filter`, but the plan has a key `Rows Removed by Join Filter` instead.

![image](https://user-images.githubusercontent.com/187342/84501374-b477d900-acb6-11ea-836d-0a497f120bd4.png)

This is on Postgres 11.4. Unsupported version maybe? (Time to upgrade anyway. ;))

When the JSON input is manually fixed, it works like a charm.

**Comment by pgiraud** [comment]
Thanks for the detail. This will be helpful to fix the issue.
Depending on the node types, "Rows removed by Filter" or "Rows removed by Join Filter" are valid even on older versions of Postgres.
Thanks for the report. I'll edit the issue title if you don't mind.

**Comment by pgiraud** [comment]
@pestaa A fix has been added.
Just for my information: are you using the github.io service or explain.dalibo.com ?

**Comment by pestaa** [comment]
Thank you Pierre!

I first found the github.io page and for my lonely case very much prefer it (don't need sharing).

Now, if you were to research the market, I can say that if my team was growing, we would look into an on-premise query plan database, possibly paid. My employer requires that our query strings not leave network boundaries. Hope this helps.
