### ISSUE TITLE
Direct link on a node

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#241]
It would be nice to be able to get an URL which leads to the details of a node. 

Use case: “The problem is in this node there ” (among 100 other nodes)

The node would appear at the center, expanded  with all details.

**Comment by blogh** [comment]
The Links are awesome. 
It would be cool to have a link to the stats also.

**Comment by pgiraud** [comment]
@blogh do you mean the global stats? or the selected node stat?

**Comment by blogh** [comment]
yes the global stats !

**Comment by pgiraud** [comment]
> It would be cool to have a link to the stats also.

Fixed via #374
