### ISSUE TITLE
Is there any way to send data to PEV without copy/pasting?

### ISSUE THREAD

**Issue by arp242** [dalibo/pev2#253]
Right now my app's admin interface has a little `textarea` where I can type or copy queries to and get the explain back:

![screenshot_2020-08-04-23-10-20_border](https://user-images.githubusercontent.com/1032692/89310798-ca4abe80-d6a7-11ea-8e78-b8ed6c3788fe.png)

It's pretty useful for me. For most purposes the standard explain output is enough for me, but for some more complex ones I'd like to send it to PEV somehow; is there any way to add a "send to PEV" button which sends something like:

    http://example.com/pev2?query=select[..]&explain=[..]

And then have it appear in PEV? Or perhaps in some other way.

This would be really helpful, as it avoids having to copy/paste stuff all the time! Come to think of it, this would also be useful for other people as well, as you could create a generic CLI tool which opens the browser instead of doing the `psql < query.sql > explain` thing and then manually copy/pasting.

I tried looking around in the source a bit to see if there's any way to do it, but as far as I could find there isn't any way to do this yet? I'm not very familiar with VueJS or SPA-type development in general, so I struggled a bit properly grokking the code so perhaps I missed something 😅

One restriction here might be URL size limits; I'm not sure what the limits on that are in current browsers. I'm not sure if there's any way to accept POST form data in a pure client-side JavaScript app? 🤔

Thanks!

**Comment by raine** [comment]
I made this tool`[1]` for easily sending query plans and queries to explain.dalibo.com. It automatically adds the `EXPLAIN ANALYZE ...` instruction to a query before submitting it along with the plan to the service.

However, it does not work anymore. I think the POST endpoint was removed because of security concerns, and now submission is done purely on the client-side. It now says nothing is stored until you share a query plan visualization. This is not optimal for programmatic use. Any chance you could consider adding that POST endpoint back?

`[1]`: https://github.com/raine/pg-explain/blob/master/pg-explain

**Comment by pgiraud** [comment]
@raine while answering @arp242 and giving several options for his resquest, I figured out that posting plans to explain.dalibo.com was broken. I'm currently trying to fix this.
By the way, I haven't heard about your tool. Thanks for sharing.

**Comment by raine** [comment]
Upon more careful look, on the contrary to what I said just now, it appears that the POST endpoint is in fact still there. It just behaves slightly differently, and the documentation on the about page`[1]` is out of date. Example on the about page expects a redirect, but the endpoint responds with a JSON that has an ID for the posted plan.

But I managed to fix my script to be compatible with the new behavior.

```
~ % echo 'select 1' > query.sql
~ % pg-explain query.sql -- postgres
https://explain.dalibo.com/plan/let
```

`[1]`: https://explain.dalibo.com/about

**Comment by arp242** [comment]
Ahh, I missed there was a POST thingy already, I'll look some further in to that later!

**Comment by pgiraud** [comment]
Hi @arp242,

If you are using `psql`, you should give a look at https://postgres.ai/blog/plan-exporter/

For the purpose of your app's admin interface I see two options:
 - integrate PEV2 as a VueJS component directly in your application. See https://github.com/dalibo/pev2#integrated.
 - POST your plan (and query) to https://explain.dalibo.com. I have added an example of an HTML code showing how to use it (see https://explain.dalibo.com/about).
