### ISSUE TITLE
Last ~50px at the bottom of the page are hidden in firefox

### ISSUE THREAD

**Issue by CaselIT** [dalibo/pev2#267]
Hi, thanks for this free and very useful tool!

In firefox (v81) the last ~50px of the page are cut (seems to be the height of the nav bar).

Here is an example with a sample plan "With cte".
![image](https://user-images.githubusercontent.com/16175304/92457267-4dd65e80-f1c4-11ea-84d2-ebe90f830a1c.png)

The bottom of CTE t_energy is not visible.
Note that plan does not matter, I just used it since it's one of the sample ones. It also happen if there are no cte.

**Comment by pgiraud** [comment]
Thanks for the report. Will give it a look as soon as possible.

**Comment by pgiraud** [comment]
A fix for the issue has been committed. I expect to do a new release soon.

**Comment by pgiraud** [comment]
FYI it has been deployed on https://explain.dalibo.com

**Comment by CaselIT** [comment]
working fine now. Thanks for the quick fix!
