### ISSUE TITLE
No clue that the left pane has more information on the right

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#269]
As just discussed:

On a small screen, when the left pane is not wide enough, and the tree deep enough, you see only the tree, not the horizontal lines. 

So a new user has no visual clue that it must expand the left pane. There is no scrolling bar at the bottom.

**Comment by pgiraud** [comment]
Fixed via https://github.com/dalibo/pev2/commit/81fce79a4307e9a6c2cbfd4fa70b7674ea5c06f8

**Comment by Krysztophe** [comment]
merci !
