### ISSUE TITLE
Allow sorting on table

### ISSUE THREAD

**Issue by lrweck** [dalibo/pev2#273]
Hi!

First of all, thanks for this tool! It's great!

Can you include the possibility to sort the table by clicking on the header:

![image](https://user-images.githubusercontent.com/26086198/93365031-a7233b00-f81f-11ea-8e34-73f5b3419ba4.png)

**Comment by pgiraud** [comment]
Can you please have a try at http://bluecarto.free.fr/pev2/sorted_tables and tell me if it matches your needs?

**Comment by lrweck** [comment]
Yep, that's what I was thinking... works great too!
