### ISSUE TITLE
Extract automatically Query when it was pasted in the Plan field

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#281]
Example : https://explain.dalibo.com/plan/JY , "Raw" tab

The query was pasted with the, before " QUERY PLAN". I suppose that is possible to cut at " QUERY PLAN ". So the query would appear in the "Query" tab.

(Yes, this is for lazy people, but that's the whole point of IT.)

**Comment by pgiraud** [comment]
I'm afraid it would require a bit too much work.

**Comment by Krysztophe** [comment]
Even in most simple cases?

**Comment by pgiraud** [comment]
Contributions are welcome. ;-)
