### ISSUE TITLE
(v13) Incremental Sort

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#291]
Example: https://explain.dalibo.com/plan/iSn

This is a new node

1) Missing info:
On this line, only the 1st field appears in Misc:
```
Full-sort Groups: 312500  Sort Method: quicksort  Average Memory: 26kB  Peak Memory: 26kB
```

2) Show the pre-sorted fields

pev2 shows as title of the node:
```
INCREMENTAL SORT
by c2, c3
```
And you must go to the Misc tab to see:
```
Sort Key | c2   c3
Presorted Key | c2
```

I propose to change the title to show that the sort operation is made on c3, perhaps on of these ways:
```
by c3 (presorted: c2)
by c2 (presorted) , c3
by (c2)  c3
```

**Comment by pgiraud** [comment]
Can you please provide the query with which you obtained this result?
I'm actually interested to get the equivalent in JSON format.

**Comment by bdsvc-github** [comment]
Deployment starting to ephemeral!

**Comment by bdsvc-github** [comment]
Deployed to ephemeral!
