### ISSUE TITLE
support passing EXPLAIN result & query via location.hash

### ISSUE THREAD

**Issue by derhuerst** [dalibo/pev2#292]
Thanks for this awesome tool!

I'm trying to automate my PostgreSQL query development workflow by writing [a small CLI helper](https://github.com/derhuerst/pev2-cli) that will open pev2. For this, **there would have to be a way to pass the `EXPLAIN` result & query via the URL** (e.g. `location.hash`).

I'd be happy to submit a PR if you tell me where to but the logic for this!

**Comment by pgiraud** [comment]
Is it for local use only? Or are you willing to use explain.dalibo.com service?
The service is already able to receive POST requests.
https://explain.dalibo.com/about

Also, you might want to consider plan-exporter which already works well.
https://github.com/agneum/plan-exporter#command-line-options

**Comment by derhuerst** [comment]
> Is it for local use only? Or are you willing to use explain.dalibo.com service?
> The service is already able to receive POST requests.

I would like to use pev2 offline, so using the online service is not an option.

Now I'm thinking about it again, my CLI tool could use the same mechanism that explain.dalibo.com uses to pass the data to the visualisation code.

**Comment by pgiraud** [comment]
> I would like to use pev2 offline, so using the online service is not an option.

Makes sense.
I haven't tried to implement anything that reads the URL parameters because the URL length is limited and we'll most probably reach the limits very often.

> Now I'm thinking about it again, my CLI tool could use the same mechanism that explain.dalibo.com uses to pass the data to the visualisation code. Is there documentation for it?

The code for the service has not been published unfortunately. It uses a backend written with Flask.
What you could probably do is run you're own web application instead of running the already built one.
https://github.com/dalibo/pev2#integrated-in-a-web-application

Then you should be able to write the data directly in the HTML or use some POST requests.

If you need some inspiration, the application delivered in the pev2.tar.gz archive is actually built using the following code : https://github.com/dalibo/pev2/tree/master/example
It's also the application that is used when you run `npm run serve` in the pev2 directory.

Don't hesitate to ask me whenever you're stuck. I'll try to give a hand as much as I can.

**Comment by derhuerst** [comment]
> What you could probably do is run you're own web application instead of running the already built one.
> https://github.com/dalibo/pev2#integrated-in-a-web-application
> 
> Then you should be able to write the data directly in the HTML [...].
> 
> If you need some inspiration, the application delivered in the pev2.tar.gz archive is actually built using the following code : https://github.com/dalibo/pev2/tree/master/example

Cool, thanks! Will use implement that.

**Comment by derhuerst** [comment]
For my command-line tool, I would like to avoid a maintenance-heavy custom pev2 build, because that would lag behind this upstream repo. Would you mind if I PR a simple `global.setPlanData(plan, query)` into the example code?

**Comment by pgiraud** [comment]
Please go ahead.

**Comment by derhuerst** [comment]
BTW: Out-of-the-box, I had trouble getting this to build locally. On macOS 10.15.7 with Node.js 14.9.0 and the latest XCode command line tools, `node-sass` didn't build. I had to upgrade `node-sass` to `4.14.1`, then it worked.

**Comment by pgiraud** [comment]
> BTW: Out-of-the-box, I had trouble getting this to build locally. On macOS 10.15.7 with Node.js 14.9.0 and the latest XCode command line tools, `node-sass` didn't build. I had to upgrade `node-sass` to `4.14.1`, then it worked.

Thanks. I took this into account.

**Comment by jankatins** [comment]
@derhuerst any chance you share how you implemented this whole flow? Would also really like to have a way to submit a plan via curl like calls...

**Comment by pgiraud** [comment]
@jankatins You can already use curl to send plans to explain.dalibo.com. See the about page.

**Comment by derhuerst** [comment]
> @derhuerst any chance you share how you implemented this whole flow? Would also really like to have a way to submit a plan via curl like calls...

I didn‘t implement a mechanism that works with the URL or an HTTP request, I merely added [a hook to call from the JavaScript in the page itself](https://github.com/derhuerst/pev2-cli/blob/08c7ffffd0fd16fe60a37557a76727d85e4db038/inject.js).

**Comment by derhuerst** [comment]
FYI: The `setPlanData` global function introduced in #295 doesn't seem to work anymore, the [latest release](https://github.com/dalibo/pev2/releases/tag/v0.16.1) doesn't contain it anymore.

**Comment by pgiraud** [comment]
@derhuerst I can't get what's wrong. `setPlanData` still  seem to be there. https://github.com/dalibo/pev2/search?q=setPlanData

**Comment by pgiraud** [comment]
@derhuerst It seems that there's a typo in this commit. https://github.com/derhuerst/pev2-cli/commit/f1d10cf12971c9f9eeb24f2794c95e60925dbb46
You changed 0.15.0 to 0.6.0

**Comment by derhuerst** [comment]
True, thanks!

**Comment by rutchkiwi** [comment]
@derhuerst Hi, how do you use the JS linked https://github.com/derhuerst/pev2-cli/blob/08c7ffffd0fd16fe60a37557a76727d85e4db038/inject.js from the CLI? Do you need to have a server running to host the file? (or can a file:// path suffice?)
And if I may ask do you have an example script/shell alias that can be used to look at the data?

**Comment by derhuerst** [comment]
@rutchkiwi If you open pev2's `index.html` file via a `file:` URL, any code executed on/within that page is not allowed to use the [`fetch` API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) to pull the execution plain. Therefore, [`pev2-cli`](https://github.com/derhuerst/pev2-cli) temporarily starts an HTTP server to serve both pev2's assets (but with a modified `index.html` that executes `index.js`), as well as the execution plain (which `inject.js` then `fetch`es).

So essentially, `pev2-cli` does 3 things:

1. serve pev2's assets via HTTP
2. serve a modified version of pev2's `index.html` that loads & executes `inject.js`
3. serve the execution plan as `/data`
4. let `inject.js` fetch the execution plain and pass it into pev2's rendering logic.

`pev2-cli` is not only a GitHub repo, but its code [is also published to npm](https://www.npmjs.com/package/pev2-cli), so you can run `npm install pev2-cli --global` to install it into your `$PATH`, so that you can just run it as `pev2 foo.sql`.

If you don't want to use `npm` to install it, you can also build it yourself:

```shell
git clone https://github.com/derhuerst/pev2-cli.git
cd pev2-cli
npm install
npm run build
# link `pev2` executable into $PATH
ln -s cli.js /opt/bin
```

**Comment by rutchkiwi** [comment]
Ah thanks for explaining @derhuerst ! That makes sense.

**Comment by derhuerst** [comment]
Both work for me, I don't really mind what I download. What is the file name that you intend to use in the future?

**Comment by pgiraud** [comment]
Even though I don't intend to remove `index.html` in a near future, I'm about to change the links in the about page in explain.dalibo.com to point to `pev2.html`. The file name has already been changed in pev2's README.
