### ISSUE TITLE
Filters are not visible enough

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#293]
When looking at https://explain.dalibo.com/plan/8UD, you do NOT see quickly than 2 seq scans are filtered, or that the hash join at the top if filtered too. This information is hidden in the Misc tab. 

This is very important as filters are the 1st criterion to choose how to begin a plan.

Suggestions : 
  * a funnel icon somewhere in the main node box (without color, as it is already used when most lines are filtered), with Filter informations in tooltip
  * a very small pie chart, somewhere in the box,  indicating a crude proportion of the lines that have made it through the filter. eg: green on gray as long, with green = kept lines, with tooltip. The color (green, blue, red...) could depend on the proportion, so this pie could replace the existing funnel icon warning
  * an horizontal bar at the bottom of the node, with the same color code
  * a vertical bar along the right of the node, with the same color code

**Comment by pgiraud** [comment]
I've just push commits that fix this issue. I've taken your first suggestion into account. This means that when there are rows removed by the filter a grey funnel icon appears. In cases where the execution time of the node is also significant, the funnel icon appears with a color as before.

The hovering tooltip now tells the user the percentage of rows removed.

**Comment by Krysztophe** [comment]
Nice !  :+1: 
(Yes, I 'm a bit late)
