### ISSUE TITLE
Parallel display of BitMap Index Scan

### ISSUE THREAD

**Issue by lrweck** [dalibo/pev2#306]
Hi!

Plan: https://explain.dalibo.com/plan/T1k

On the leftmost nodes, there is a Parallel Bitmap Heap Scan, with a three nodes below. These don't look like they are parallelized, because there is only one "card".

**Comment by pgiraud** [comment]
This is actually what the JSON plan is tellling us. I'll have a closer look later.
Are you able to provide the same plan in text format?

**Comment by lrweck** [comment]
With text output is displays correctly: https://explain.dalibo.com/plan/faZ
