### ISSUE TITLE
Is explain.dalibo.com open source?

### ISSUE THREAD

**Issue by chdsbd** [dalibo/pev2#319]
Thanks for hosting explain.dalibo.com, it's a wonderful service! Is explain.dalibo.com open source? I was looking to see how the persistence works but I didn't find any reference within this repository.

**Comment by pgiraud** [comment]
Thanks a lot for your feedback.
I haven't pusblished the code for the service itself. I was thinking about publishing it. There's actually no reason why I wouldn't.

FYI, it's a very simple Flask application with a bit of SQLAlchemy and a postgreSQL backend of course. The database schema is very similar to the one used for explain.depesz.com. I didn't want to reinvent the wheel for this part of the application.

Can you elaborate the reason why you wanted to know how the data was persisted? Are you interested in hosting your own service for PEV2? Are you concerned about security for your data?

Also did you know that you can use the standalone (browser only) application shipped with PEV2?

**Comment by chdsbd** [comment]
Thanks for getting back to me.

I was curious how it worked and I was interested in making a PR to make the public URLs have more entropy, like GitHub Gists. So instead of a URL like https://explain.dalibo.com/plan/I18, it would be like: https://explain.dalibo.com/plan/72ad1d91513101cbb4796b59009ef6b6

**Comment by simi** [comment]
> I haven't pusblished the code for the service itself. I was thinking about publishing it. There's actually no reason why I wouldn't.

@pgiraud has that happened already? I can't find any related code.

**Comment by pgiraud** [comment]
The source code for explain.dalibo.com is available at https://github.com/dalibo/explain.dalibo.com/

**Comment by simi** [comment]
Ahh, thanks a lot! Would it be worth to mention in PR? Happy to send PR.
