### ISSUE TITLE
Supported browsers?

### ISSUE THREAD

**Issue by Giorgi** [dalibo/pev2#339]
Hello,

Which versions of which browser does this component support?

**Comment by pgiraud** [comment]
I haven't done any extensive testing.
However it is supposed to work on most modern browsers.

Did you encounter any issue with a specific browser?

**Comment by Giorgi** [comment]
I'm trying to embed it in a desktop app with a WebBrowser control and that means that the engine used is IE 11 but it doesn't work in IE 11

**Comment by pgiraud** [comment]
I just checked and unfortunately I can confirm that it doesn't work on IE11. There's a syntax error.
This may require a significant amount of work to make it compatible.

**Comment by Giorgi** [comment]
So it's unlikely to see IE 11 support?

**Comment by pgiraud** [comment]
Hi @Giorgi this morning I tried to see how difficult it would be to make it work with IE11. After a bit of time, I realized that some of the libraries PEV2 depends on have simply dropped support for IE last year. Even if I decide to use older versions of those libraries, I'm not sure I'll be able to make it work.

I'm sorry but this appears to be too much (painful) work.

I don't know anything about this WebBrowser control. Isn't there any alternative?

**Comment by Giorgi** [comment]
There is [webview2](https://docs.microsoft.com/en-us/microsoft-edge/webview2/) but it requires the installation of additional runtime by the users.

**Comment by Giorgi** [comment]
@pgiraud I decided to just display a plain text plan but have added an option for sharing plan to https://explain.dalibo.com/

You can view the tool at https://github.com/Giorgi/LINQPad.QueryPlanVisualizer

When webview2 becomes mainstream I'll probably add support for pev2

**Comment by pgiraud** [comment]
Thanks for letting me know.
I'd be very happy to see pev2 directly integrated in other tools. But as already mentioned, because of the dependance on libraries not supporting IE11, I'm not eager to fix this issue.
