### ISSUE TITLE
PG14 : New node type "tid range scan"

### ISSUE THREAD

**Issue by blogh** [dalibo/pev2#379]
This new type of node allows for a more performant access to tuples when specitying their physical position.
The ctid is composed of the page position in the table and the tuple position in the page.

```
ctid = '(block number in table, tuple number in page)'
```

Discussion : 
* https://www.postgresql.org/message-id/flat/CAMyN-kB-nFTkF=VA_JPwFNo08S0d-Yk0F741S2B7LDmYAi8eyA@mail.gmail.com

Commit fest entry :
* https://commitfest.postgresql.org/32/2924/

Setup : 

```
[local]:5438 postgres@postgres=# CREATE TABLE test(i int);
CREATE TABLE
[local]:5438 postgres@postgres=# INSERT INTO test SELECT generate_series(1,100000);
INSERT 0 100000
[local]:5438 postgres@postgres=# SET track_io_timing TO on;
SET
```

PG13 plan :  (the table is scanned completely)

```
[local]:5438 postgres@postgres=# EXPLAIN (ANALYZE,BUFFERS) SELECT * FROM test WHERE ctid > '(400,0)';
                                                 QUERY PLAN                                                 
------------------------------------------------------------------------------------------------------------
 Tid Range Scan on test  (cost=0.00..142.05 rows=9605 width=4) (actual time=0.019..2.116 rows=9600 loops=1)
   TID Cond: (ctid > '(400,0)'::tid)
   Buffers: shared hit=43
 Planning Time: 0.079 ms
 Execution Time: 3.372 ms
(5 rows)
```

PG 14 plan : (only the relevant blocks are scanned)
```
[local]:5438 postgres@postgres=# EXPLAIN (ANALYZE,BUFFERS) SELECT * FROM test WHERE ctid > '(400,0)';
                                                 QUERY PLAN                                                 
------------------------------------------------------------------------------------------------------------
 Tid Range Scan on test  (cost=0.00..142.05 rows=9605 width=4) (actual time=0.019..2.116 rows=9600 loops=1)
   TID Cond: (ctid > '(400,0)'::tid)
   Buffers: shared hit=43
 Planning Time: 0.079 ms
 Execution Time: 3.372 ms
(5 rows)
```

This is the PEV2 link for this new plan : https://explain.dalibo.com/plan/9QA

No problem on that side.

EDIT: plan with track_io_timing & buffers + PEV2 link.

**Comment by pgiraud** [comment]
Not really a big deal but I think you pasted the same plan for both 13 and 14.

**Comment by pgiraud** [comment]
Apart from the "Tid Range Scan" type not being correctly parsed in text format, I don't see anything to do specifically in PEV2.
