### ISSUE TITLE
Links to nodes from the stats tab

### ISSUE THREAD

**Issue by pgiraud** [dalibo/pev2#395]
As suggested by @blogh it would be nice to have links to nodes in the stats tabs.
For example, for a table with 2 seq scans, we could give the user a direct link to the 2 related nodes.

**Comment by pgiraud** [comment]
@blogh and others, what do you think about the following UI?

![Capture d’écran du 2021-07-05 11-30-29](https://user-images.githubusercontent.com/319774/124450788-0d645480-dd85-11eb-8dd9-d5e2843002b9.png)

We should be able to do the same for per node and per index tables as well.

**Comment by gleu** [comment]
Looks pretty nice!

**Comment by pgiraud** [comment]
Do you think the user should be able to expan/collapse the detailed info? Or maybe it's not a problem to have a very high scrollable page for the stats tab.

**Comment by gleu** [comment]
For people having huge plans (and we have some :) ), it could be interesting

**Comment by Krysztophe** [comment]
With a 100 or 1000 partitions table, some collapsing would probably help, but how? You would have one table and one node per partition, I suppose.

**Comment by blogh** [comment]
Late feedback : I used it yesterday. It's awesome. thanks.
