### ISSUE TITLE
Docker image build fails with version mismatch

### ISSUE THREAD

**Issue by neiaberau** [dalibo/pev2#401]
Hi, 

with commit 6cfaca4 I can still build the docker image, after that with 24e5d28 I get errors:

Vue packages version mismatch:

- vue@2.6.13 (/app/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.12 (/app/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./example/src/main.ts 6:0-36 10:11-15
 @ multi ./example/src/main.ts

 error  in ./example/src/views/About.vue

Module Error (from ./node_modules/vue-loader/lib/index.js):

... and some more of the same nature

**Comment by pgiraud** [comment]
Thanks for the report. This should be fixed now. Please confirm.

Can you also give me more information about your usage of PEV2? Is there any reason why you build and use docker image instead of the standalone pev2.tar.gz archive (https://github.com/dalibo/pev2#portable-on-a-usb-stick)?

**Comment by neiaberau** [comment]
a) yes, it works now again
b) nothing to do with pev2, 
    in general, non production or new software only used intermittently , is never install directly, only via docker image
    so if there is a Docker file, then it is directly used, if not a short one written
    this also has the benefit of always having the newest version (and the drawback of issues )
    regarding pev2, I just found it only two weeks ago, so far https://gitlab.com/depesz/explain.depesz.com is used, 
    currently checking differencies using them in parallel whenever a a slow query pops up
