### ISSUE TITLE
New node: Memoize

### ISSUE THREAD

**Issue by lrweck** [dalibo/pev2#429]
Hi Guys!

Can we add some info to the new Memoize node in PG14?

https://explain.dalibo.com/plan/OFO

I suggest something like:

This node is used to cache the results of the inner side of a nested loop. It avoids executing underlying nodes when the results for the current parameters are already in the cache.

Thanks for the awesome tool!

**Comment by pgiraud** [comment]
@lrweck I'm off for a few months. I just saw your feature request. I'll see what I can do from my "very" remote location.

> Thanks for the awesome tool!

Thanks for this kind message and your support.
