### ISSUE TITLE
"Rows" graph does not correctly scale when larger datasets are used

### ISSUE THREAD

**Issue by nightpool** [dalibo/pev2#445]
Right now, it looks like larger rows get truncated, instead of other rows getting scaled down to accommodate:

![image](https://user-images.githubusercontent.com/233815/150163539-5b743b93-bf33-4e71-8afa-269ae737b3f0.png)

in this image, the first two plan items have ~1,000 rows associated, and the next few have 6,000,000 rows associated! but there's very little visual difference between them.

Even when dragging the left sidebar all the way over, the issue remains:

![image](https://user-images.githubusercontent.com/233815/150163985-315980ec-c57f-409d-a978-759273073c24.png)

Since the rows aren't scaled properly, this makes it hard to interpret the graph.

**Comment by nightpool** [comment]
Maybe a logarithmic scaling function would be more appropriate here?

**Comment by pgiraud** [comment]
Interesting. Do you have a link to the plan in explain.dalibo.com (or the execution plan itself)?

**Comment by pgiraud** [comment]
@nightpool I couldn't reproduce this. Can you please provide an example?

**Comment by nightpool** [comment]
Let me see if I can anonymize an example to send you

**Comment by pgiraud** [comment]
@nightpool I'm still interested by an example. To anonymize a plan, you can use "I want this plan to be obfuscated before saving" in depesz.
