### ISSUE TITLE
Parallel Execution inside CTE

### ISSUE THREAD

**Issue by lrweck** [dalibo/pev2#47]
"stacked cards" view for parallel nodes are not showing when executed inside a CTE.

Also Partial aggregates could be identified differently, since they are running in parallel workers.

Plans and query: [https://pastebin.com/FZua2AUs](https://pastebin.com/FZua2AUs)

EDIT: It's behind the CTE panel.
![image](https://user-images.githubusercontent.com/26086198/65076460-67591780-d96f-11e9-9add-d6c114851f5f.png)

**Comment by pgiraud** [comment]
Thanks for the report and the example plan. That'll be tricky to fix. The stacked cards display is a bit hackish.

**Comment by lrweck** [comment]
It still happens:
![image](https://user-images.githubusercontent.com/26086198/65617220-c2ec5c00-df92-11e9-81e2-eed771c2ecb7.png)


Plan used: https://pastebin.com/cxgUkCCN

**Comment by pgiraud** [comment]
To me, the issue is fixed since we can now see all the workers "stacked cards". They are no hidden behind the CTE panel.
I agree this is not perfect since it goes beyond the edge but I couldn't find a way to extend the CTE panel.
