### ISSUE TITLE
Drag and drop doesn't work on FF

### ISSUE THREAD

**Issue by mulchy** [dalibo/pev2#471]
On https://explain.dalibo.com/ drag and drop works great on chrome, but does nothing on Firefox. 

I tried to look into it a little bit and noticed that the event listeners for dragenter are firing and updating the class appropriately, but the listener for `drop` never fires. I am wondering if perhaps the dragleave event is firing first and is removing the drop handler.

**Comment by mulchy** [comment]
Also thanks for making this, this website is sweet

**Comment by pgiraud** [comment]
Thanks for the report.

**Comment by pgiraud** [comment]
I can't seem to reproduce this issue. Please reopen if you still have problems.
