### ISSUE TITLE
"Couldn't parse plan": hint clueless users that swap fields

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#472]
If a user swaps the _Plan_ and _Query_ fields (ie: he puts `EXPLAIN SELECT 1 ;` in Plan, and `QUERY PLAN ....` and so on in _Query_, which is after all the most intuitive way when copy-pasting both query and plan in a hurry), the result is simply « Couldn't parse plan ».

To avoid to lose time to try reformatting a perfectly fine plan, it is possible to add a message like this in the error box ?
>Did you put a SQL query in the _Plan_ field?

This is not possible to detect all possible cases, but these are the most current symptoms:
  * `QUERY PLAN`,  `(cost=`, `rows=` `width=` are present in the _Query_ field
  * `SELECT`, `EXPLAIN`, `UPDATE`, `INSERT`, `WITH` is the 1st word of the _Plan_ field
  * `=#` or `;`  appear in the Plan field.

(Please don't ask why I came to this idea :roll_eyes: )

**Comment by pgiraud** [comment]
Closing as won't fix.

The [new "won't fix message"](https://github.com/dalibo/pev2/pull/660) showing the failing plan may help.
