### ISSUE TITLE
Direct link on a node should open the node informations

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#478]
In following examples, clicking on the link leads directly to a node (it is highlighted), but I would expect it to be expanded by default, at least when this plan was not opened before.
I'm not sure that it should be expanded when clicking in the tree on the left, but it could be a choice in the settings.

https://explain.dalibo.com/plan/mZe#plan/node/1
https://explain.dalibo.com/plan/e4WW#plan/node/3
https://explain.dalibo.com/plan/mZe#plan/node/1

Bonus point if this is possible to add a direct link to a tab (eg : IO & Buffers, or Misc).

**Comment by pgiraud** [comment]
Already taken into account.
