### ISSUE TITLE
how to build All-in-one version?

### ISSUE THREAD

**Issue by hn5092** [dalibo/pev2#488]

**Comment by pgiraud** [comment]
Can you please elaborate?
Why do you need to build the all-in-one version? It is already built for you and available as an asset each time a release is done.

**Comment by hn5092** [comment]
i found it, i want modify some thing

**Comment by hn5092** [comment]
thx

**Comment by pgiraud** [comment]
> i found it, i want modify some thing

I'm curious. What are you changing? Are you customizing it to your needs?

**Comment by hn5092** [comment]
not customizing change, I want users to parse our database plan. it's like pg plan

**Comment by hn5092** [comment]
it's a good project to show a plan with pg, but I think, if it supports any query engine, it will be nice?   I think it's can abstract some interface to parser string with every query engine

**Comment by hn5092** [comment]
https://github.com/dalibo/pev2/issues/489   create a new issue
