### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier "emitter".

### ISSUE THREAD

**Issue by gael-efluid** [dalibo/pev2#508]
Bonjour,
Avec la dernière version [standalone](https://www.github.com/dalibo/pev2/releases/latest/download/index.html) de pev2, la page ne se charge pas et dans le DEBUG du navigateur (Chrome 104.0.5112.81 / Edge 103.0.1264.62 / Firefox 101.0.1) j'obitens l'erreur "_Uncaught TypeError: Failed to resolve module specifier "emitter"._'
![image](https://user-images.githubusercontent.com/83600500/183407971-adad0e59-1277-4fa4-a8d3-63b66f71cf55.png)

Avez-vous une idée d’où viendrait le problème ?

Cordialement,
Gaël

**Comment by pgiraud** [comment]
Merci pour le rapport de bug. Je vais tâcher de le résoudre rapidement.
Si besoin, il est toujours possible d'utiliser celui-ci : https://github.com/dalibo/pev2/releases/download/v1.2.0/index.html

**Comment by pgiraud** [comment]
J'ai trouvé une correction pour le problème et j'ai poussé une nouvelle version.
