### ISSUE TITLE
Feedback about the new design

### ISSUE THREAD

**Issue by madtrick** [dalibo/pev2#521]
👋  First of all thanks a lot for keeping this project alive and improving it over time. Very appreciated.

I'm opening this issue to give you some feedback regarding one of the most recent releases. Up until a couple of weeks ago it was possible to expand different nodes at the same time and show different detail views ("General", "IO & Buffers", ...)  for each of them. This was great for different reasons: compare nodes, investigate different nodes at a time, take screenshots with all the relevant details visible, etc. To my surprise this no longer the behaviour. Now if one clicks on a node, the details view for that node is absolutely positioned on the viewport and as soon as another node is clicked this detail view updates with the contents for that node, which breaks the flow I describes earlier.

Could this behaviour be made optional?

**Comment by pgiraud** [comment]
Hello.
Thanks a lot for your feedback. It's very useful.

Actually It took me a long time to take the decision to get rid of the "show the details in the graph" and instead show only one at a time.
I asked my colleagues for their feedback and the choice whether to keep it or not was not obvious.

Technically speaking, given the fact that the new design (including zoom) relies on SVG, it's a bit more difficult to keep the old behavior. Though not impossible.

I may wait for more feedback / complains about this change before I decide to reimplement old behavior.

**Comment by pgiraud** [comment]
An other option I was thinking of was to pin the detail popover. Thus, it would be possible to show more than one detail popover at a time.

**Comment by madtrick** [comment]
> An other option I was thinking of was to pin the detail popover. Thus, it would be possible to show more than one detail popover at a time.

I guess that could be a workaround but it my mind it's still nicer to have the expanded details view right on the node. With the popover I have to do some additional mental work to connect the popover to the node in the tree which can be annoying on large trees.

**Comment by gael-efluid** [comment]
Hello,
I join madtrick on this one : I found the previous behaviour really userfriendly/easier to understand and analyse a plan.

Kind regards,

**Comment by nightpool** [comment]
I had the exact same experience. It's much harder to use the new version to compare different nodes.

**Comment by pgiraud** [comment]
@nightpool @madtrick @gael-efluid @tulak
FYI a new version of pev2 has been deployed on explain.dalibo.com

The previous behavior has been reimplemented. I hope it works for you.
