### ISSUE TITLE
Scrolling on node's details view doesn't work

### ISSUE THREAD

**Issue by madtrick** [dalibo/pev2#522]
With the new design, where the details of node are always shown in the top right corner, if the node dimensions are larger than that of the visible screen the node can't be scrolled to show those details. Attempts to scroll will most likely zoom out the whole plan diagram.

On the screenshot I'm showing a node where I can't see all the details of the "Misc" tab because I can't scroll.

![image](https://user-images.githubusercontent.com/48772/184810357-7ac7beb5-5b55-44e0-aa1a-a1db0e687c6b.png)

**Comment by pgiraud** [comment]
Hi, thanks for reporting this issue. I'll try to fix it as soon as possible.

**Comment by pgiraud** [comment]
The detail is not shown in a separate panel but in place as before. See !525.
Will be deployed on explain.dalibo.com soon.
