### ISSUE TITLE
New graph design glitchy in Safari

### ISSUE THREAD

**Issue by sfcgeorge** [dalibo/pev2#523]
The nodes, labels and edges all seem disconnected so scrolling and zooming don't work properly.

<img width="1920" alt="Screenshot 2022-08-30 at 10 59 54 am" src="https://user-images.githubusercontent.com/885003/187428340-f73269c3-d6bf-4b3f-b290-70267239bb95.png">

Latest Safari `Version 15.6.1` 
Also occurs in latest Safari Technology Preview `Release 152 (Safari 16.0, WebKit 17615.1.2.3)`
so probably happens on all iPad browsers too

**Comment by pgiraud** [comment]
Oh. That's very annoying. Thanks for the report.

**Comment by pgiraud** [comment]
This is unfortunately due to a bug in Safari: https://bugs.webkit.org/show_bug.cgi?id=23113
Also see https://stackoverflow.com/questions/54221528/safari-is-not-respecting-scaling-applied-to-a-foreignobject

I unfortunately don't have any workaround for that.
