### ISSUE TITLE
Cannot copy node link anymore

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#524]
With the new design, it is impossible to right-click somewhere in a node to copy its URL.
With the old design I add an explicit link to righ-click.

Yes, it is simply available in the address bar, and obvious once you know it. But nothing else shows that is possible to create a direct link to a node.

Perhaps just add a link icon somewhere in the node box?

**Comment by pgiraud** [comment]
Fixed via !525.

To be deployed soon.
