### ISSUE TITLE
pev2 fails to reconstruct a copy-pasted plan

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#546]
This is the correct plan : https://explain.dalibo.com/plan/a4ea04414h99666e

This is the same as  copy-pasted from a Linux terminal : https://explain.dalibo.com/plan/03cf572ce27c576c
in this case, the automatic reconstruction of the cut lines fails.  It does not even show an error, but totally bogus plan with only a Seq Scan instead of the real plan.

**Comment by Krysztophe** [comment]
Any idea when the fix will be available on explain.dalibo.com?

**Comment by pgiraud** [comment]
> Any idea when the fix will be available on explain.dalibo.com?

It has just been deployed.

**Comment by Krysztophe** [comment]
Super,  merci !  :+1:
