### ISSUE TITLE
IO times along Execution & planning times  along throughput

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#574]
I think that the time spent in IO times should be put as `s` or `ms ` next to Execution time and Planning Time, instead (of the throughput.
![image](https://user-images.githubusercontent.com/22391138/224951006-a0d695cd-f6df-498f-9d54-039ab78dec9b.png)

Examples:  https://explain.dalibo.com/plan/dd68b1ag616e05h6#plan and https://explain.dalibo.com/plan/fbdh9341hfb81897#plan : the plans are the same, the time is different, the IO throughput is different, but I don't know immediately if this IO time is a big part of the query or not. The IO time gives a clue about the cache effect. In these plans, you just have to go to the worst node to have the IO time, or to the left pane, but it would tedious in a more complicated plan.

(Throughput is nice though, just less important than absolute time. Of course i'd love to see both at once.)

**Comment by Krysztophe** [comment]
Another plan with many partitions for testing.

**Comment by pgiraud** [comment]
What do you think about that:
![Screenshot from 2024-08-21 14-17-10](https://github.com/user-attachments/assets/c7c7c554-f88f-4a00-86cb-5d42765bc351)
![Screenshot from 2024-08-21 14-18-36](https://github.com/user-attachments/assets/ed8e6c45-9a0b-457d-b33c-2006d2f5a92f)

Should the throughput (average speed) be displayed permanently or in a tooltip on hover to save some space?

**Comment by Krysztophe** [comment]
Nice!

There is enough place for now, so I think you can let the speed as it is.
