### ISSUE TITLE
Cannot click in Workers in a parallelized plan

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#575]
Plan : https://explain.dalibo.com/plan/9f82253bd4b2c29f#plan

I cannot click on `Worker 0` or any other without folding the node. 

Tested on FFox and Chromium.

![image](https://user-images.githubusercontent.com/22391138/224955876-512473ea-2006-4e3e-8cf2-528e79a900cb.png)

**Comment by pgiraud** [comment]
Duplicate for #566

**Comment by Krysztophe** [comment]
Sorry, I should have checked existing bugs
