### ISSUE TITLE
Emphasize filter

### ISSUE THREAD

**Issue by anayrat** [dalibo/pev2#614]
Hello,

I think we should emphasize filter clause on a node.
For example, on this plan https://explain.dalibo.com/plan/91af244fg9d1ec21#plan

We can see there are many lines filtered :
![image](https://github.com/dalibo/pev2/assets/6862220/e57437b7-5fb1-41ac-a6f7-66a63874d1b4)

But the filter, is a little bit hidden in the misc tab 
![image](https://github.com/dalibo/pev2/assets/6862220/bdfe72aa-8ef1-401e-a0b0-209defea4260)

Regards,

**Comment by Krysztophe** [comment]
I agree. This happens very often.

Add a _Filter_ tab between _General_ and _IO buffers_ ?  I don't know if it could bear an icon.
