### ISSUE TITLE
Having issues with POST requests from pgBadger reports

### ISSUE THREAD

**Issue by kmoradha** [dalibo/pev2#619]
I've set up a private installation of the PEV2 demo, using the provided index.html file, so that I can visualize explain plans using this excellent tool without have to upload details outside of our network.

I'm also using pgBadger to analyze PostgreSQL logs configured to include explain plans via auto_explain.  The pgBadger reports are configured to send the explain plans to my private PEV2 demo installation (via POST requests) using the `--explain-url` argument, but the demo install doesn't seem to be accepting the parameters, i.e. when I click "Explain Plan" from the pgBadger report, I just get the blank "New Plan" form in PEV2.

I'm using latest pgBadger (12.2) and latest PEV2 (1.8.0), and I've used my browser dev panel to confirm that the request parameters are being sent in the POST request.  I've also tried this with both Firefox and Chrome.

Any ideas what I'm doing wrong here?  I know I can just copy-and-paste the explain plan from the pgBadger report to the "New Plan" form, but I was hoping for a little integration magic. :)

**Comment by chaosong** [comment]
<img width="780" alt="image" src="https://github.com/user-attachments/assets/c23032b0-f252-4d02-b88d-1637bab2815f" />
"Explain Plan"  is not clickable and there is html error in "<div id="query-d-explain-2-2" class="sql sql-largesize"><i class="glyphicon icon-compass"></i><b>Explain plan</b></a></div>"

pgbadger: 12.2
pev2: self-hosted lastest dalibo/explain.dalibo.com

**Comment by pgiraud** [comment]
Thanks for the report @chaosong. I'll have a look as soon as possible.
