### ISSUE TITLE
Reverse query & plan

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#62]
The interface asks for 1) the plan  and 2) the query below.

This is the reverse from the natural order when pasting an EXPLAIN ANALYZE from psql, and I often reverse plan and query.

Suggestion : Reverse the order two fields.

Alternative: automatically recognize the mistake, swap the content of the two fields.

Better alternative: one single field, a single cut-and-paste from psql (EXPLAIN query & plan) and the interface would separate query and plan alone.

**Comment by pgiraud** [comment]
Given the fact that the query is not mandatory, I prefer to keep the plan field shown first.
The suggested alternatives will require too much work in my opinion.
I will close this issue as won't fix for now.
