### ISSUE TITLE
Handle buffers option output

### ISSUE THREAD

**Issue by frost242** [dalibo/pev2#65]
Hello,

Thanks for this tool. Is it possible to handle the Buffers output (obtained by EXPLAIN (ANALYZE, BUFFERS)) and add the possibility this as graph metric. It's a cumulative metric and is quite useful to identify costly operations.
An example output is: 
Buffers: shared hit=199998 read=2988

Thanks

Kind regards

**Comment by pgiraud** [comment]
Hello @frost242 

Can you please provide an example of a complete plan with relevant buffers information?

**Comment by pgiraud** [comment]
Considering this plan, what would you think we should show in the interface?
```
                        QUERY PLAN
-------------------------------------------------------
 Sort (cost=172682.84..175182.84 rows=1000000 width=37) (actual time=632.796..756.958 rows=1000000 loops=1)
   Sort Key: c1
   Sort Method: external sort  Disk: 45952kB
   Buffers: shared hit=3910 read=4424, temp read=5744 written=5744
   ->  Seq Scan on foo  (cost=0.00..18334.00 rows=1000000 width=37) (actual time=0.134..110.617 rows=1000000 loops=1)
         Buffers: shared hit=3910 read=4424
 Total runtime: 811.308 ms
```

**Comment by pgiraud** [comment]
@frost242 This is now available in the new "diagram" component. See #130

**Comment by lrweck** [comment]
> @frost242 This is now available in the new "diagram" component. See #130

Hmm I can't see the option to show the new diagram.

**Comment by pgiraud** [comment]
@lrweck it has not been deployed on explain.dalibo.com yet. It's currently available on https://dalibo.github.io/pev2

**Comment by frost242** [comment]
Hi Pierre,
Thanks for implenting this feature. It looks nice this way but the hits/reads are accounted in a cumulative manner.
For example, take this plan :
```
  Sort  (cost=466.79..478.18 rows=4557 width=621) (actual time=56.291..56.994 rows=4557 loops=1)
   Sort Key: c.relname, a.attnum
   Sort Method: quicksort  Memory: 2542kB
   Buffers: shared hit=101
   ->  Hash Join  (cost=32.22..189.87 rows=4557 width=621) (actual time=1.222..21.562 rows=4557 loops=1)
         Hash Cond: (c.relnamespace = n.oid)
         Buffers: shared hit=101
         ->  Hash Join  (cost=30.99..171.60 rows=4557 width=504) (actual time=1.165..14.218 rows=4557 loops=1)
               Hash Cond: (a.attrelid = c.oid)
               Buffers: shared hit=100
               ->  Seq Scan on pg_attribute a  (cost=0.00..128.57 rows=4557 width=239) (actual time=0.011..1.857 rows=4557 loops=1)
                     Buffers: shared hit=83
               ->  Hash  (cost=23.22..23.22 rows=622 width=265) (actual time=1.133..1.133 rows=622 loops=1)
                     Buckets: 1024  Batches: 1  Memory Usage: 126kB
                     Buffers: shared hit=17
                     ->  Seq Scan on pg_class c  (cost=0.00..23.22 rows=622 width=265) (actual time=0.009..0.256 rows=622 loops=1)
                           Buffers: shared hit=17
         ->  Hash  (cost=1.10..1.10 rows=10 width=117) (actual time=0.040..0.041 rows=10 loops=1)
               Buckets: 1024  Batches: 1  Memory Usage: 10kB
               Buffers: shared hit=1
               ->  Seq Scan on pg_namespace n  (cost=0.00..1.10 rows=10 width=117) (actual time=0.015..0.019 rows=10 loops=1)
                     Buffers: shared hit=1
 Settings: effective_cache_size = '3GB', effective_io_concurrency = '2', work_mem = '32MB'
 Planning Time: 2.641 ms
 Execution Time: 58.154 ms
(25 lignes)
```

There's one hit for pg_namespace, 17 hits for pg_class and 83 hits for pg_attribute. Then,17+83=100 hits are accounted on the hash join between pg_attribute and pg_class, but this particular operation doesn't do any hit or read. The accounted access are cumulative as this works for time accounting between the different nodes of a plan.
I hope I'm clear enough. Let me know if you need more information.
Regards

**Comment by pgiraud** [comment]
Closing this issue in favor of https://github.com/dalibo/pev2/issues/211

**Comment by pgiraud** [comment]
@frost242 A user just reported an issue #240 showing that the buffers values are not necessarily cumulative. By any chance, do you have an explanation?
