### ISSUE TITLE
Docker build is broken

### ISSUE THREAD

**Issue by mdavid-plntr** [dalibo/pev2#74]
Hi,
I've followed the docker build/run instructions on CONTRIBUTING.md but I get an 403 - Forbidden error from Nginx.

Looking at the NGINX logs it seems there is an index.html file missing:

```[error] 6#6: *9 rewrite or internal redirection cycle while internally redirecting to "/index.html"```

Any idea how to fix this? I don't have a lot of experience with `npm` or `Vue.js`

Thanks!

**Comment by pgiraud** [comment]
@mdavid-plntr this should be fixed now. Can you please have a try?
May I ask you why and how you are using PEV2?
Would a downloadable archive containing all the relevant HTML/JS/CSS files do the job?

**Comment by mdavid-plntr** [comment]
Hi @pgiraud ,
Thanks for the quick reply. I'm using PEV to get a better understanding of how the planer is working in PG. Mostly for dev work at the moment.

A downloadable archive would be great, since I can use that wherever I need without having to setup a whole VueJS stack.

Unfortunately it doesn't seem like that commit fixed the issue.
`Step 7/8 : COPY --from=0 /app/dist-app /app
COPY failed: stat /var/lib/docker/overlay2/008cf657905e4f695eb731218ca0e3b39a0c768b30e807136a2eabff1cff8d7c/merged/app/dist-app: no such file or directory`

from what can tell, the `npm run build` step is only generating the js and map files in the dist directory. But it's missing all the other ones.

**Comment by pgiraud** [comment]
My bad. Didn't pay enough attention.
This should be fixed now. Please update.

What about using https://dalibo.github.io/pev2 or https://explain.dalibo.com ?

**Comment by mdavid-plntr** [comment]
Yes that fixed it. Thanks!

Those sites are great but not an option for me since there are some concerns about sending the explain plans outside of our network.

**Comment by pgiraud** [comment]
This may not be clear enough but in the github.io demo app the plans are not sent anywhere. You can check in the network tab. Everything is done in the browser. This is not the case with explain.dalibo.com where the plans are actually stored in a database to be shared.
