### ISSUE TITLE
Metrics & checkboxes

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pev2#91]
Is it possible to have all metrics as checkboxes, like 'Costs' currently ? I'd like to have all at once, especially when colors give quick hints.

I've thought of this because currently you can have a "Cost" box show twice if you choose Cost as metric and in the checkbox.

**Comment by pgiraud** [comment]
Closing this issue for now.
There's no checkbox in the view options for the metrics any more.
Also in my opinion, showing more than one metric bar at a time would lead to unreadable information.
